function generateResultsTables(results, ablationResults, ablationNames, baselineResults, outputDir)
% Generate summary tables as CSV files

    % Table 4: Performance comparison
    fid = fopen(fullfile(outputDir, 'Table4_PerformanceComparison.csv'), 'w');
    fprintf(fid, 'Method,Accuracy(%%),Sensitivity(%%),Specificity(%%),F1-Score(%%),AUC\n');

    methodNames = fieldnames(baselineResults);
    for m = 1:length(methodNames)
        br = baselineResults.(methodNames{m});
        fprintf(fid, '%s,%.2f ± %.2f,%.2f ± %.2f,%.2f ± %.2f,%.2f ± %.2f,%.4f ± %.4f\n', ...
            methodNames{m}, mean(br.accuracy)*100, std(br.accuracy)*100, ...
            mean(br.sensitivity)*100, std(br.sensitivity)*100, ...
            mean(br.specificity)*100, std(br.specificity)*100, ...
            mean(br.f1score)*100, std(br.f1score)*100, ...
            mean(br.auc), std(br.auc));
    end
    fprintf(fid, 'FQI-DNN-XAI (Proposed),%.2f ± %.2f,%.2f ± %.2f,%.2f ± %.2f,%.2f ± %.2f,%.4f ± %.4f\n', ...
        mean(results.accuracy)*100, std(results.accuracy)*100, ...
        mean(results.sensitivity)*100, std(results.sensitivity)*100, ...
        mean(results.specificity)*100, std(results.specificity)*100, ...
        mean(results.f1score)*100, std(results.f1score)*100, ...
        mean(results.auc), std(results.auc));
    fclose(fid);

    % Table 6: Ablation study
    fid = fopen(fullfile(outputDir, 'Table6_AblationStudy.csv'), 'w');
    fprintf(fid, 'Configuration,Accuracy(%%),Sensitivity(%%),Specificity(%%),Precision(%%),F1-Score(%%),AUC\n');
    for a = 1:size(ablationResults, 1)
        fprintf(fid, '%s,%.2f,%.2f,%.2f,%.2f,%.2f,%.4f\n', ...
            ablationNames{a}, ablationResults(a, :) * 100);
    end
    fclose(fid);

    fprintf('  Result tables saved as CSV.\n');
end
